import { motion } from "framer-motion";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqs = [
  { q: "What is AI Visibility?", a: "AI Visibility refers to how prominently your brand, products, or content appear in responses generated by AI models like ChatGPT, Gemini, and Perplexity. As more users rely on AI for information, your AI visibility directly impacts brand awareness and traffic." },
  { q: "How does LLMClicks track AI visibility?", a: "LLMClicks monitors how major AI models respond to industry-relevant prompts, tracking when and how your brand is mentioned, cited, or recommended. We provide detailed analytics and trend data over time." },
  { q: "Is this different from traditional SEO?", a: "Yes. Traditional SEO focuses on search engine rankings, while AI visibility focuses on how LLMs reference your brand in conversational responses. Both are important, but AI visibility requires different optimization strategies." },
  { q: "How long does an AI Visibility Audit take?", a: "A comprehensive audit typically completes within minutes. You'll receive a detailed report with scores, competitor comparisons, and actionable recommendations." },
  { q: "Do I need technical knowledge to use LLMClicks?", a: "Not at all. LLMClicks is designed to be user-friendly with intuitive dashboards and clear, actionable insights. No coding or technical expertise required." },
  { q: "Is there a free trial available?", a: "Yes! We're currently in beta and offering free access. Sign up to start analyzing your AI visibility today with no credit card required." },
];

const FAQSection = () => (
  <section className="section-padding">
    <div className="container mx-auto max-w-3xl">
      <motion.div
        className="text-center mb-12"
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >
        <div className="highlight-pill mb-4 mx-auto w-fit">FAQ</div>
        <h2 className="font-display text-3xl md:text-5xl font-extrabold mb-5">
          Got <span className="gradient-text">Questions?</span>
        </h2>
      </motion.div>

      <Accordion type="single" collapsible className="space-y-3">
        {faqs.map((faq, i) => (
          <AccordionItem key={i} value={`faq-${i}`} className="bold-card border-none px-8">
            <AccordionTrigger className="text-left font-display font-bold text-lg hover:no-underline py-5">{faq.q}</AccordionTrigger>
            <AccordionContent className="text-muted-foreground leading-relaxed text-base pb-6">{faq.a}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  </section>
);

export default FAQSection;
